### PR TITLE
Firebase

### LINKED ISSUE #5: [Important] Add access to a database
I suggest trying with Firebase. If it does not work easily we will look into other solutions.

### PR DESCRIPTION
**Pull request by vood00child**
Closes #5

### CODE REVIEW

File: src/Activity/TrainWithExercises/index.js [hunk 1]
```diff
@@ -13,22 +13,28 @@ class TrainWithExercise extends React.Component {
...
     this.setState({hasChosenExercise: true, index: index})
   }
 
-  getBackToExercise = () => {
-    this.setState({hasChosenExercise: false})
+  recordExerciseActivity = (userAnswer, studentAnswer) => {
+    var parallelogramTitle = (parallelogramData[this.state.index].src).split('/')
+    this.newActivityRef.child('/item_exercise').set(parallelogramTitle[parallelogramTitle.length - 1])
+    this.newActivityRef.child('/activity_type').set('exercise')
+    this.newActivityRef.child('/knowledge').set(this.props.student.knowledgeParallelograms)
```
Comment (lfaucon) [inline src/Activity/TrainWithExercises/index.js]: This line crashes for me. Register -> Start a game -> Select and exercise -> answer VRAI -> crash

screen shot 2018-07-24 at 10 58 27
