### PR TITLE
Issue 63

### LINKED ISSUE #63: Add avatar to train component

### LINKED ISSUE #77: [bug] Fix wrong gender issue
Sometime the gender of the teacher avatar defaults to female while it should be male

### PR DESCRIPTION
**Pull request by vood00child**
closes #63 
closes #77

### CODE REVIEW

File: src/Activity/ChooseActivity/index.js [hunk 1]
```diff
@@ -10,24 +10,28 @@ import Grid from "@material-ui/core/Grid";
...
-    height: "25%"
+  activityChoice: {
+    height: "100%"
   },
   button: {
     position: "relative",
-    height: 300,
-    width: 300,
+    height: "100%",
+    width: "400%",
```
Comment (vood00child) [inline src/Activity/ChooseActivity/index.js]: I don't know why I had to set this to 400% to display the buttons (otherwise they are compressed)

File: src/Activity/ChooseActivity/index.js [hunk 2]
```diff
@@ -142,88 +180,149 @@ class ChooseActivity extends React.Component {
...
       <div className={classes.root}>
+        <div className={classes.sessionTimeline}>
+          <SessionTimeline sessionRef={sessionRef} />
+        </div>
         <Grid
           container
-          className={classes.sessionTimeline}
-          justify="center"
-          alignItems="center"
+          justify="space-evenly"
```
Comment (vood00child) [inline src/Activity/ChooseActivity/index.js]: this triggers a warning in the console

**Comment by vood00child** [comment]
There is also a bug with the bubble to fix when the user has not enough points for the activity
